### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by mansi1710** [NJACKWinterOfCode/Alzheimer-s-Disease-Prediction-using-3D-MRI-scans#1]
Vary the batch size to facilitate better training.

**Comment by Sai-Adarsh** [comment]
code1.py
code2.py
LeNet_swmdc.py
vgg16_model.py 

should we vary batch size in every file for better training or one file is enough ?

**Comment by mansi1710** [comment]
Trying on transfer learning models will be better. Anyway, you can try varying the batch size for any of the codes.
